version: '2'
services:
  rabbit:
    image: "rabbitmq:3-management-alpine"
    hostname: rabbit
    networks:
      - nvf-net
    ports:
      - "15672:15672"
    expose:
    - "5672"
    - "15672"
    environment:
      - RABBITMQ_DEFAULT_PASS=pass
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_VHOST=vhost
  mysql:
    image: "mysql"
    networks:
      - nvf-net
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  flask:
    image: "python:2.7-alpine"
    networks:
      - nvf-net
    ports:
      - "5000:5000"
    links:
      - rabbit
      - mysql
    volumes:
      - ./flask:/usr/src/app
    working_dir:
        "/usr/src/app"
    entrypoint:
      - /usr/src/app/entrypoint.sh
  express:
    image: "node:7-alpine"
    networks:
      - nvf-net
    ports:
      - "8000:8000"
    links:
      - rabbit
      - mysql
    volumes:
      - ./express:/usr/src/app
    working_dir:
        "/usr/src/app"
    entrypoint:
      - /usr/src/app/entrypoint.sh
  restify:
    image: "node:7-alpine"
    networks:
      - nvf-net
    ports:
      - "8080:8080"
    links:
      - rabbit
      - mysql
    volumes:
      - ./restify:/usr/src/app
    working_dir:
        "/usr/src/app"
    entrypoint:
      - /usr/src/app/entrypoint.sh
networks:
  nvf-net:
    driver: bridge
